%%	Filename:  interfaces/matlab/simulink/make.m
%%	Author:    Andrei Herdt
%%	Version:
%%	Date:      2012
%%
%% consistency check
if ( exist( [pwd, '/make.m'],'file' ) == 0 )
    disp( 'ERROR: Run this make script directly within the directory' );
    disp( '       <mpc-walkgen>/interfaces/matlab/simulink, please.' );
    return;
end

%% Set flags
make_dependencies;

IFLAGS  = ['-I. -I', MPC_WALKGEN_PATH, 'include',' -I',EIGEN_PATH,' -I',QPOASES_PATH,'include/',' -I',QLD_PATH,' ' ];
%IFLAGS  = ['-I. -I',MPC_WALKGEN_PATH,'include',' -I',EIGEN_PATH,'-I',QPOASES_PATH,' -L',MPC_WALKGEN_LIBRARY_PATH,' ' ];

if (ispc == 0)
    CPPFLAGS  = [ IFLAGS, '-lblas -lstdc++ -D__cpluplus -D__MATLAB__ -O -DLINUX', ' ' ]; %% -D__NO_COPYRIGHT__ -D__SUPPRESSANYOUTPUT__
else
    CPPFLAGS  = [IFLAGS, '-v', ' -D__WIN32__',' -D__NO_COPYRIGHT__',' -D__SUPPRESSANYOUTPUT__',' -D__STDC__', ' ' ]; %% -D__NO_COPYRIGHT__ -D__SUPPRESSANYOUTPUT__
    %CPPFLAGS = [IFLAGS, ' -pedantic', ' -Wshadow', ' -O3', ' -finline-functions', ' -DLINUX', ' -D__NO_COPYRIGHT__'];
    %CPPFLAGS  = [IFLAGS, ' ' ];
end

MPC_WALKGEN_OBJECTS =	[	MPC_WALKGEN_PATH, 'src/com-body.cpp ',...
    MPC_WALKGEN_PATH, 'src/foot-body.cpp ',...
    MPC_WALKGEN_PATH, 'src/interpolation.cpp ',...
    MPC_WALKGEN_PATH, 'src/lssol-parser.cpp ',...
    MPC_WALKGEN_PATH, 'src/realclock.cpp ',...
    MPC_WALKGEN_PATH, 'src/orientations-preview.cpp ',...
    MPC_WALKGEN_PATH, 'src/qp-builder.cpp ',...
    MPC_WALKGEN_PATH, 'src/qp-matrix.cpp ',...
    MPC_WALKGEN_PATH, 'src/heuristic-preview.cpp ',...
    MPC_WALKGEN_PATH, 'src/qp-solver.cpp ',...
    MPC_WALKGEN_PATH, 'src/qp-vector.cpp ',...
    MPC_WALKGEN_PATH, 'src/qpoases-parser.cpp ',...
    MPC_WALKGEN_PATH, 'src/qld-parser.cpp ',...
    MPC_WALKGEN_PATH, 'src/rigid-body-system.cpp ',...
    MPC_WALKGEN_PATH, 'src/rigid-body.cpp ',...
    MPC_WALKGEN_PATH, 'src/state-fsm.cpp ',...
    MPC_WALKGEN_PATH, 'src/tools.cpp ',...
    MPC_WALKGEN_PATH, 'src/types.cpp ',...
    MPC_WALKGEN_PATH, 'src/dynamics-builder.cpp ',...
    MPC_WALKGEN_PATH, 'src/debug.cpp ',...
    MPC_WALKGEN_PATH, 'src/walkgen.cpp ', ' ' ];
%MPC_WALKGEN_OBJECTS = [MPC_WALKGEN_LIBRARY_PATH,'mpc-walkgen.lib ', ' '];

QPOASES_OBJECTS =	[	QPOASES_PATH, 'src/SQProblem.cpp ',...
    QPOASES_PATH, 'src/QProblem.cpp ',...
    QPOASES_PATH, 'src/QProblemB.cpp ',...
    QPOASES_PATH, 'src/Bounds.cpp ',...
    QPOASES_PATH, 'src/Constraints.cpp ',...
    QPOASES_PATH, 'src/SubjectTo.cpp ',...
    QPOASES_PATH, 'src/Indexlist.cpp ',...
    QPOASES_PATH, 'src/Flipper.cpp ',...
    QPOASES_PATH, 'src/Utils.cpp ',...
    QPOASES_PATH, 'src/Options.cpp ',...
    QPOASES_PATH, 'src/Matrices.cpp ',...
    QPOASES_PATH, 'src/realtimeclock.cpp ',...
    QPOASES_PATH, 'src/MessageHandling.cpp ', ' ' ];

QLD_OBJECTS =	[	QLD_PATH, 'qld.cpp ', ' ' ];

%QPOASES_OBJECTS = [	QPOASES_LIB_PATH, 'BLASReplacement.lib ',...
%    QPOASES_LIB_PATH, 'LAPACKReplacement.lib ',...
%    QPOASES_LIB_PATH, 'libqpOASES.lib ',...
%    QPOASES_LIB_PATH, 'libqpOASESextras.lib ',' ' ];

% BLAS_OBJECTS = [ BLAS_LIB_PATH, 'libgoto2.a' ];

% DEBUGFLAGS = ' ';
DEBUGFLAGS = ['-D_DEBUG -g',' '];
%DEBUGFLAGS = ' -g CXXDEBUGFLAGS=''$CXXDEBUGFLAGS -Wall -pedantic -Wshadow'' ';

NAME = 'walkgen_sfun';
%% Compile
eval(['mex -output ', NAME, ' ', CPPFLAGS, DEBUGFLAGS, [NAME,'.cpp ', QLD_OBJECTS, MPC_WALKGEN_OBJECTS, QPOASES_OBJECTS]]);
disp([NAME, '.', eval('mexext'), ' successfully created!']);

%% Set path and copy libraries
path(path, pwd);
%path(path, [pwd,'/',MPC_WALKGEN_LIBRARY_PATH]);
% Copy libraries
%copyfile([MPC_WALKGEN_LIBRARY_PATH,'\mpc-walkgen.dll'],[pwd,'/mpc-walkgen.dll']);
%copyfile([MPC_WALKGEN_LIBRARY_PATH,'\mpc-walkgen.lib'],[pwd,'/mpc-walkgen.lib']);
%% Clear
clear EIGEN_PATH QPOASES_PATH QPOASES_LIB_PATH MPC_WALKGEN_PATH MPC_WALKGEN_LIBRARY_PATH IFLAGS CPPFLAGS MPC_WALKGEN_OBJECTS DEBUGFLAGS NAME QPOASES_OBJECTS QLD_PATH QLD_OBJECTS